# Site settings
title: Sridhar Chandrashekar
twitter_username: Sridharc20
name: Sridhar Chandrashekar

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://sridharcblog.wordpress.com/
 - title: GitHub
   url: https://github.com/sridharc20
 - title: StackOverflow
   url: http://stackoverflow.com/users/6458371/sridhar-c
 - title: DZone
   url: https://dzone.com/users/2785140/sridharc.html
   
 - title: LinkedIn
   url: https://in.linkedin.com/in/sridharc20

#Any buzzword skills you want to include
skills:
 - Spring MVC
 - Spring Boot
 - Java
 - SQL
 - REST
 - Tech Architecture
 - Amazon Web Services
 - Cloud Computing
 - Cloud Native Application Architecture
 - Microservices
 - Docker

#Work experience is required
roles:
 - title: Jr Technical Architect
   start: April 2016
   end: Ongoing
   employer: Accel Frontline Limited - A CAC holdings group company
   description: Part of CTO office, an R&D division of the company working on cutting edge technologies. Provides the architectural consultancy and software design review across the organization.
         1. AWS 
         2. Cloud Native Application Architecture
         3. Microservice Architecture approach - Docker container
         
 - title: Software Engineer
   start: November 2013
   end: March 2016
   employer: MarketShare Infotech India Pvt Ltd a Neustar Company
   description: Part of the Application Engineering team. Responsible for solving the production issues within the SLA. Fixing the production issues, worked on Change Requests during application releases.  Developed few API projects.Created a Sqoop script and implemented on the test and production environment which will load the data from Hive tables (HDFS) to the Oracle Database. Technologies worked - Java 1.7,Hibernate, REST API, RabbitMQ, Linux on Amazon EC2,MySQL,Oracle, Jira, Git , Stash, Sqoop.

 - title: Senior Engineer
   start: July 2011
   end: October 2013
   employer: Mindtree Ltd
   description: A range of functional and technical roles, primarily working on client sites in Financial Services.
      Client - American Express
#Education is required
education:
 - level: Bachelor of Engineering (B.E.)
   date: 2011
   college: Siddaganga Institute of Technology Tumkur
   university: Visveswaraya Technological University
   CGPA: 8.40/10

#This section is optional (as is the image link below)


#List of interesting Github repo/projects to include - optional
github:
 - Sridharc20/Spring-boot-docker-project

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/6458371/sridhar-c
   flairimageurl: http://stackoverflow.com/users/flair/6458371.png
  
#Mobile apps section is optional
apps:


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java APIâ€™s and frameworks. I have recently worked with Spring Boot, Netflix OSS stack in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks<br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Java, Hibernate, Spring MVC framework and REST.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with Git, Maven, Gradle and Jenkins. <br/><br/>
   
